apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - install.yaml

images:
  - name: ghcr.io/jvillalbaj2lc/k8-hot-shrunk-requests
    newTag: latest # Change this to a specific version tag (e.g. v0.1.0)
